# Generated by Django 2.1.4 on 2019-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('state', models.CharField(choices=[('ABIA', 'ABIA'), ('ADAMAWA', 'ADAMAWA'), ('AKWA IBOM', 'AKWA IBOM'), ('KANO', 'KANO')], max_length=20)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('tyre_make', models.CharField(max_length=200)),
                ('tyre_guage', models.IntegerField(blank=True, null=True)),
                ('valve_position', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('NONE', 'NONE')], max_length=20)),
                ('job_number', models.IntegerField(blank=True, null=True)),
                ('tank_position', models.CharField(choices=[('BALLON', 'BALLON'), ('SPRING', 'SPRING')], max_length=200)),
                ('registration_number', models.CharField(max_length=200)),
                ('transporter', models.CharField(max_length=200)),
                ('chasis_number', models.CharField(max_length=200)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('expiary_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
            ],
        ),
    ]
